#!/bin/bash
#Project 1
#add name to this line if you contribute to the code: Logan Toler
#Team 2; Zachary Brewer, Kenilkumar Patel
#Automated Apache Install

#Install and Start Apache/httpd
echo "Installing Apache..." | tee -a apache-install.log 
yum update -y >> apache-install.log
yum install httpd -y >> apache-install.log
service httpd start >> apache-install.log
chkconfig httpd on >> apache-install.log
echo "Installation Complete!" | tee -a apache-install.log

#Variables
version=$(date +"%m_%d_%Y_%H_%M_%S")
CFG="/etc/httpd/conf/httpd.conf_$version"


#create back up
echo "Backing up httpd.conf..." | tee -a apache-install.log
cp /etc/httpd/conf/httpd.conf $CFG
echo done | tee -a apache-install.log
