#!/bin/bash
#Project 1
#add name to this line if you contribute to the code: Logan Toler
#Team 2; Zachary Brewer, Kenilkumar Patel
#Automated Apache Install

#Install and Start Apache/httpd
echo "Installing Apache..." | tee -a apache-install.log 
yum update -y >> apache-install.log
yum install httpd -y >> apache-install.log
service httpd start >> apache-install.log
chkconfig httpd on >> apache-install.log
echo "Installation Complete!" | tee -a apache-install.log

#Variables
version=$(date +"%m_%d_%Y_%H_%M_%S")
CFG="/etc/httpd/conf/httpd.conf"
CFG_BAK="/etc/httpd/conf/httpd.conf_$version"


#create back up and configure httpd.conf
echo "Backing up httpd.conf..." | tee -a apache-install.log
cp /etc/httpd/conf/httpd.conf $CFG_BAK
echo "Backup Complete" | tee -a apache-install.log
echo "Configuring httpd.conf..." | tee -a apache-install.log
sed -i 's/ServerAdmin root@localhost/ServerAdmin cit470.sp2018.team2@gmail.com/g' $CFG >> apache-install.log
sed -i 's/#ServerName www.example.com:80/ServerName 10.2.7.229:80/g' $CFG >> apache-install.log
sed -i 's/UserDir disabled/#UserDir disabled/g' /etc/httpd/conf.d/userdir.conf >> apache-install.log
sed -i 's/#UserDir public_html/UserDir public_html/g' /etc/httpd/conf.d/userdir.conf >> apache-install.log
